[package]
name = "audio-multiplexer-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.65"
jack = "0.10.0"
ringbuf = "0.3.1"
soundtouch-sys = "1.0.0"
